In [27]:
import numpy as np
import sys
from IPython.display import display, Math
import sympy as sp

sys.path.append('../modulos')

In [9]:
from visualizacion import mostrar_matriz
from matrices import convertir_a_sympy

## NumPy: La Biblioteca Fundamental para la Computación Científica en Python

**NumPy** es una biblioteca de código abierto para el lenguaje de programación Python que soporta la creación y manipulación de vectores, matrices y estructuras de datos de mayor dimensión. Es ampliamente utilizada en el ámbito de la ciencia de datos, la ingeniería y la investigación científica debido a su eficiencia y facilidad de uso.

### Principales Usos de NumPy:
- **Operaciones matemáticas**: NumPy ofrece funciones matemáticas avanzadas que operan sobre arrays y matrices de manera eficiente.
- **Álgebra lineal**: Proporciona herramientas para realizar operaciones de álgebra lineal como productos de matrices, cálculo de determinantes y sistemas de ecuaciones lineales.
- **Transformadas de Fourier**: Permite realizar transformadas de Fourier para analizar frecuencias en señales y otros datos.
- **Generación de números aleatorios**: Incluye funciones para generar números aleatorios y realizar operaciones estadísticas.
- **Integración con otras bibliotecas**: NumPy es compatible con otras bibliotecas de Python como Pandas, Matplotlib y SciPy, formando la base para la mayoría de las tareas de computación científica.

### Métodos y Ejemplos de Uso:

- `.array`método para crear una array de numpy

In [11]:
# Crear un array de una dimensión
a = np.array([1, 2, 3])
mostrar_matriz(
    convertir_a_sympy(a)
)


# Crear un array de dos dimensiones (matriz)
b = np.array([[1, 2, 3], [4, 5, 6]])
mostrar_matriz(
    convertir_a_sympy(b)
)

⎡1⎤
⎢ ⎥
⎢2⎥
⎢ ⎥
⎣3⎦

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

- `.+` operador para sumar arrays, `-` operador para restar arrays.

In [14]:
# ejemplo suma la resta es similar pero con su operador
c = np.array([[1, 2, 3]])
d = np.array([[4, 5, 6]])

mostrar_matriz(
    convertir_a_sympy(c + d)
)

[5  7  9]

- `.dot` método para el producto escalar de matrices

In [15]:
mostrar_matriz(
    convertir_a_sympy(np.dot(c, d.T))
)

[32]

`.sin` metodo para obtener la función seno, `.cos` para obtener la función coseno, `tan`para obtener la tangente.

In [21]:
e = np.array([0, np.pi/2, np.pi])
print(np.sin(e))

# Exponencial
print(np.exp(c))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[[ 2.71828183  7.3890561  20.08553692]]


Los métodos que hacen referencia al álgebra lineal suelen estar precedidos de .linelg

- `linalg.inv`metodo para obtener la inversa de una matriz

In [22]:
f = np.array([[1, 2], [3, 4]])
f_inv = np.linalg.inv(f)

mostrar_matriz(
    convertir_a_sympy(f_inv)
)

⎡-2.0  1.0 ⎤
⎢          ⎥
⎣1.5   -0.5⎦

- `linalg.eig` metodo para obtener los autovalores u autovectores de una matriz

In [32]:
vals, vecs = np.linalg.eig(f)

print(vals)
print(vecs)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


NumPy es una herramienta esencial para cualquier persona que trabaje con datos o necesite realizar cálculos numéricos complejos en Python. Su sintaxis intuitiva y su rendimiento optimizado la convierten en una elección popular entre los profesionales y entusiastas de la programación.